@base_url = http://localhost:3333
@subscriber_id = {{subscription.response.body.subscriberId}}

# @name subscription
POST {{base_url}}/subscriptions
Content-Type: application/json

{
	"name": "Matheus de Gondra",
	"email": "matheus@mail.com"
}
###

GET {{base_url}}/invite/{{subscriber_id}} 
###

GET {{base_url}}/subscribers/{{subscriber_id}}/ranking/clicks