@base_url = http://localhost:3333
@subscriber_id = {{subscription.response.body.subscriberId}}

# @name subscription
POST {{base_url}}/subscriptions
Content-Type: application/json

{
	"name": "Usuário indicado 2",
	"email": "indicado2@mail.com",
	"referrer": "e2dbd1db-fe7a-4fa9-8e3b-26c1768043f0"
}
###

GET {{base_url}}/invite/{{subscriber_id}} 
###

GET {{base_url}}/subscribers/{{subscriber_id}}/ranking/clicks
###

GET {{base_url}}/subscribers/e2dbd1db-fe7a-4fa9-8e3b-26c1768043f0/ranking/count
###

GET {{base_url}}/subscribers/e2dbd1db-fe7a-4fa9-8e3b-26c1768043f0/ranking/position
###

GET {{base_url}}/ranking