services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      - "63790:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
